export const actionTypes = {
    FETCH_PRODUCTS_LOADING : "FETCH_PRODUCTS_LOADING",
    FETCH_PRODUCTS_SUCCESS : "FETCH_PRODUCTS_SUCCESS",
    FETCH_PRODUCTS_ERROR : "FETCH_PRODUCTS_ERROR",
    ADD_TO_CART : "ADD_TO_CART",
    REMOVE_FROM_CART : "REMOVE_FROM_CART",
}